security:
  require-ssl:true
server:
    port: 9443
    ssl:
      enabled: true
      key-alias: spring
      key-store: classpath:saml/keystore.jks
      key-store-password: secret
    servlet:
      context-path: /

spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:templates/
    suffix: .html
  security:
    saml2:
      network:
        read-timeout: 10000
        connect-timeout: 5000
      service-provider:
        entity-id: arun-spring-saml
        alias: arun-spring-saml
        sign-metadata: false
        sign-requests: false
        want-assertions-signed: true
        single-logout-enabled: true
        encrypt-assertions: false
        name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
        keys:
          active:
            name: sp-signing-key-1

        providers:
          - alias: enter-into-dummybot-saml
            metadata: https://login.microsoftonline.com/2cba1354-f501-42c4-911c-0980e8d322b9/federationmetadata/2007-06/federationmetadata.xml?appid=bd687118-c0ae-4da0-93a2-e24a864f1563
            skip-ssl-validation: true
            link-text: enter-into-dummybot-saml
            authentication-request-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST